[build]
  # Command to build your site
  command = "npm run build"
  # Directory containing the built static assets relative to the base directory
  publish = "public"
  # Directory (relative to the root) that contains the serverless functions
  # The Remix Vite build should output the Netlify function handler correctly.
  # Netlify usually detects functions automatically if placed in a standard 'netlify/functions'
  # directory or if configured via the adapter. The Remix build output structure
  # should handle this.

[dev]
  # Local development command (optional, Netlify Dev uses this)
  command = "npm run dev"
  # Port for local development server
  port = 3000 # Or whatever port your Remix dev server uses (Vite default is 5173)
  # The target port for the serverless functions
  targetPort = 5173 # Match your Remix dev server port

# Redirects and rewrites are crucial for SPAs and SSR frameworks like Remix
[[redirects]]
  # Redirect all requests to the Netlify function handler for Remix
  from = "/*"
  to = "/.netlify/functions/server" # Default Remix function name convention
  status = 200
  # Force prevents shadowing by static files in the publish directory (e.g., index.html)
  # This ensures Remix handles all routing.
  force = true

[[redirects]]
  # Explicitly serve static assets from the build output directory
  # Netlify automatically serves files from the 'publish' directory,
  # but this ensures assets generated by the build in 'public/build' are served correctly.
  from = "/build/*"
  to = "/build/:splat"
  status = 200
